In [1]:
import pandas as pd

In [3]:
raw_csv_data = pd.read_csv("Absenteeism_data.csv")

In [4]:
raw_csv_data

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
695,17,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,28,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,18,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,25,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,15,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [6]:
# Copt of the Dataset
df_copy = raw_csv_data.copy()

In [7]:
df_copy

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
695,17,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,28,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,18,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,25,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,15,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [10]:
# Panda max colums and rows to see all data
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [13]:
raw_csv_data

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,3,23,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,10,22,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,20,23,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,14,19,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,1,22,13/07/2015,235,11,37,239.554,29,3,1,1,8
10,20,1,20/07/2015,260,50,36,239.554,23,1,4,0,8
11,20,1,14/07/2015,260,50,36,239.554,23,1,4,0,8
12,20,11,15/07/2015,260,50,36,239.554,23,1,4,0,8
13,3,11,15/07/2015,179,51,38,239.554,31,1,0,0,1
14,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,4
15,24,14,17/07/2015,246,25,41,239.554,23,1,0,0,8
16,3,23,17/07/2015,179,51,38,239.554,31,1,0,0,2
17,3,21,27/07/2015,179,51,38,239.554,31,1,0,0,8
18,6,11,30/07/2015,189,29,33,239.554,25,1,2,2,8
19,33,23,05/08/2015,248,25,47,205.917,32,1,2,1,2
20,18,10,12/08/2015,330,16,28,205.917,25,2,0,0,8
21,3,11,03/08/2015,179,51,38,205.917,31,1,0,0,1
22,10,13,10/08/2015,361,52,28,205.917,27,1,1,4,40
23,20,28,14/08/2015,260,50,36,205.917,23,1,4,0,4
24,11,18,17/08/2015,289,36,33,205.917,30,1,2,1,8
25,10,25,24/08/2015,361,52,28,205.917,27,1,1,4,7
26,11,23,04/08/2015,289,36,33,205.917,30,1,2,1,1
27,30,28,12/08/2015,157,27,29,205.917,22,1,0,0,4
28,11,18,19/08/2015,289,36,33,205.917,30,1,2,1,8
29,3,23,28/08/2015,179,51,38,205.917,31,1,0,0,2
30,3,18,17/08/2015,179,51,38,205.917,31,1,0,0,8
31,2,18,27/08/2015,235,29,48,205.917,33,1,1,5,8
32,1,23,27/08/2015,235,11,37,205.917,29,3,1,1,4
33,2,18,17/08/2015,235,29,48,205.917,33,1,1,5,8
34,3,23,17/08/2015,179,51,38,205.917,31,1,0,0,2
35,10,23,17/08/2015,361,52,28,205.917,27,1,1,4,1
36,11,24,04/08/2015,289,36,33,205.917,30,1,2,1,8
37,19,11,20/08/2015,291,50,32,205.917,23,1,0,0,4
38,2,28,21/08/2015,235,29,48,205.917,33,1,1,5,8
39,20,23,28/08/2015,260,50,36,205.917,23,1,4,0,4
40,27,23,01/09/2015,184,42,27,241.476,21,1,0,0,2
41,34,23,07/09/2015,118,10,37,241.476,28,1,0,0,4
42,3,23,01/09/2015,179,51,38,241.476,31,1,0,0,4
43,5,19,08/09/2015,235,20,43,241.476,38,1,1,0,8
44,14,23,09/09/2015,155,12,34,241.476,25,1,2,0,2
45,34,23,13/09/2015,118,10,37,241.476,28,1,0,0,3
46,3,23,14/09/2015,179,51,38,241.476,31,1,0,0,3
47,15,23,24/09/2015,291,31,40,241.476,25,1,1,1,4
48,20,22,04/09/2015,260,50,36,241.476,23,1,4,0,8
49,15,14,14/09/2015,291,31,40,241.476,25,1,1,1,32
50,20,0,21/09/2015,260,50,36,241.476,23,1,4,0,0
51,29,0,28/09/2015,225,26,28,241.476,24,1,1,2,0
52,28,23,08/09/2015,225,26,28,241.476,24,1,1,2,2
53,34,23,15/09/2015,118,10,37,241.476,28,1,0,0,2
54,11,0,22/09/2015,289,36,33,241.476,30,1,2,1,0
55,36,0,29/09/2015,118,13,50,241.476,31,1,1,0,0
56,28,18,16/09/2015,225,26,28,241.476,24,1,1,2,3
57,3,23,23/09/2015,179,51,38,241.476,31,1,0,0,3
58,13,0,30/09/2015,369,17,31,241.476,25,1,3,0,0
59,33,23,11/09/2015,248,25,47,241.476,32,1,2,1,1
60,3,23,18/09/2015,179,51,38,241.476,31,1,0,0,3
61,20,23,25/09/2015,260,50,36,241.476,23,1,4,0,4
62,3,23,06/10/2015,179,51,38,253.465,31,1,0,0,3
63,34,23,13/10/2015,118,10,37,253.465,28,1,0,0,3
64,36,0,14/10/2015,118,13,50,253.465,31,1,1,0,0
65,22,23,15/10/2015,179,26,30,253.465,19,3,0,0,1
66,3,23,16/10/2015,179,51,38,253.465,31,1,0,0,3
67,28,23,16/10/2015,225,26,28,253.465,24,1,1,2,3
68,34,23,06/10/2015,118,10,37,253.465,28,1,0,0,3
69,28,23,14/10/2015,225,26,28,253.465,24,1,1,2,2
70,33,23,21/10/2015,248,25,47,253.465,32,1,2,1,2
71,15,23,22/10/2015,291,31,40,253.465,25,1,1,1,5
72,3,23,21/10/2015,179,51,38,253.465,31,1,0,0,8
73,28,23,21/10/2015,225,26,28,253.465,24,1,1,2,3
74,20,19,22/10/2015,260,50,36,253.465,23,1,4,0,16
75,15,14,13/10/2015,291,31,40,253.465,25,1,1,1,8
76,28,28,20/10/2015,225,26,28,253.465,24,1,1,2,2
77,11,26,21/10/2015,289,36,33,253.465,30,1,2,1,8
78,10,23,23/10/2015,361,52,28,253.465,27,1,1,4,1
79,20,28,30/10/2015,260,50,36,253.465,23,1,4,0,3
80,3,23,05/11/2015,179,51,38,306.345,31,1,0,0,1
81,28,23,04/11/2015,225,26,28,306.345,24,1,1,2,1
82,3,13,05/11/2015,179,51,38,306.345,31,1,0,0,8
83,17,21,12/11/2015,179,22,40,306.345,22,2,2,0,8
84,15,23,19/11/2015,291,31,40,306.345,25,1,1,1,5
85,14,10,02/11/2015,155,12,34,306.345,25,1,2,0,32
86,6,22,09/11/2015,189,29,33,306.345,25,1,2,2,8
87,15,14,16/11/2015,291,31,40,306.345,25,1,1,1,40
88,28,23,18/11/2015,225,26,28,306.345,24,1,1,2,1
89,14,6,20/11/2015,155,12,34,306.345,25,1,2,0,8
90,28,23,18/11/2015,225,26,28,306.345,24,1,1,2,3
91,17,21,25/11/2015,179,22,40,306.345,22,2,2,0,8
92,28,13,20/11/2015,225,26,28,306.345,24,1,1,2,3
93,20,28,27/11/2015,260,50,36,306.345,23,1,4,0,4
94,33,28,02/11/2015,248,25,47,306.345,32,1,2,1,1
95,28,28,10/11/2015,225,26,28,306.345,24,1,1,2,3
96,11,7,11/11/2015,289,36,33,306.345,30,1,2,1,24
97,15,23,26/11/2015,291,31,40,306.345,25,1,1,1,3
98,33,23,01/12/2015,248,25,47,261.306,32,1,2,1,1
99,34,19,01/12/2015,118,10,37,261.306,28,1,0,0,64
100,36,23,02/12/2015,118,13,50,261.306,31,1,1,0,2
101,1,26,02/12/2015,235,11,37,261.306,29,3,1,1,8
102,28,23,03/12/2015,225,26,28,261.306,24,1,1,2,2
103,20,26,04/12/2015,260,50,36,261.306,23,1,4,0,8
104,34,19,08/12/2015,118,10,37,261.306,28,1,0,0,56
105,10,22,09/12/2015,361,52,28,261.306,27,1,1,4,8
106,28,28,10/12/2015,225,26,28,261.306,24,1,1,2,3
107,20,28,11/12/2015,260,50,36,261.306,23,1,4,0,3
108,28,23,15/12/2015,225,26,28,261.306,24,1,1,2,2
109,10,22,16/12/2015,361,52,28,261.306,27,1,1,4,8
110,34,27,11/12/2015,118,10,37,261.306,28,1,0,0,2
111,24,19,18/12/2015,246,25,41,261.306,23,1,0,0,8
112,28,23,18/12/2015,225,26,28,261.306,24,1,1,2,2
113,28,23,06/01/2016,225,26,28,308.593,24,1,1,2,1
114,34,19,04/01/2016,118,10,37,308.593,28,1,0,0,1
115,34,27,05/01/2016,118,10,37,308.593,28,1,0,0,1
116,14,18,05/01/2016,155,12,34,308.593,25,1,2,0,8
117,28,27,06/01/2016,225,26,28,308.593,24,1,1,2,2
118,27,23,07/01/2016,184,42,27,308.593,21,1,0,0,2
119,28,28,07/01/2016,225,26,28,308.593,24,1,1,2,2
120,28,27,08/01/2016,225,26,28,308.593,24,1,1,2,1
121,34,27,11/01/2016,118,10,37,308.593,28,1,0,0,2
122,28,27,12/01/2016,225,26,28,308.593,24,1,1,2,2
123,34,27,12/01/2016,118,10,37,308.593,28,1,0,0,2
124,34,27,13/01/2016,118,10,37,308.593,28,1,0,0,2
125,34,27,14/01/2016,118,10,37,308.593,28,1,0,0,2
126,34,27,15/01/2016,118,10,37,308.593,28,1,0,0,2
127,34,27,11/01/2016,118,10,37,308.593,28,1,0,0,2
128,34,27,12/01/2016,118,10,37,308.593,28,1,0,0,2
129,22,18,12/01/2016,179,26,30,308.593,19,3,0,0,8
130,11,18,12/01/2016,289,36,33,308.593,30,1,2,1,8
131,34,27,13/01/2016,118,10,37,308.593,28,1,0,0,2
132,27,23,21/01/2016,184,42,27,308.593,21,1,0,0,2
133,34,27,28/01/2016,118,10,37,308.593,28,1,0,0,2
134,34,27,25/01/2016,118,10,37,308.593,28,1,0,0,0
135,28,23,26/01/2016,225,26,28,308.593,24,1,1,2,1
136,11,22,28/01/2016,289,36,33,308.593,30,1,2,1,3
137,27,23,05/02/2016,184,42,27,302.585,21,1,0,0,1
138,24,1,03/02/2016,246,25,41,302.585,23,1,0,0,8
139,3,11,10/02/2016,179,51,38,302.585,31,1,0,0,8
140,14,28,11/02/2016,155,12,34,302.585,25,1,2,0,2
141,6,23,11/02/2016,189,29,33,302.585,25,1,2,2,8
142,20,28,12/02/2016,260,50,36,302.585,23,1,4,0,2
143,11,22,12/02/2016,289,36,33,302.585,30,1,2,1,8
144,31,11,08/02/2016,388,15,50,302.585,24,1,0,0,8
145,31,1,09/02/2016,388,15,50,302.585,24,1,0,0,8
146,28,28,15/02/2016,225,26,28,302.585,24,1,1,2,2
147,28,23,09/02/2016,225,26,28,302.585,24,1,1,2,2
148,22,23,16/02/2016,179,26,30,302.585,19,3,0,0,1
149,27,23,23/02/2016,184,42,27,302.585,21,1,0,0,8
150,28,25,25/02/2016,225,26,28,302.585,24,1,1,2,3
151,18,18,15/02/2016,330,16,28,302.585,25,2,0,0,8
152,18,23,16/02/2016,330,16,28,302.585,25,2,0,0,1
153,28,23,17/02/2016,225,26,28,302.585,24,1,1,2,1
154,6,19,25/02/2016,189,29,33,302.585,25,1,2,2,8
155,19,28,01/03/2016,291,50,32,343.253,23,1,0,0,2
156,20,19,01/03/2016,260,50,36,343.253,23,1,4,0,8
157,30,19,08/03/2016,157,27,29,343.253,22,1,0,0,3
158,17,17,15/03/2016,179,22,40,343.253,22,2,2,0,8
159,15,22,16/03/2016,291,31,40,343.253,25,1,1,1,8
160,20,13,02/03/2016,260,50,36,343.253,23,1,4,0,8
161,22,13,03/03/2016,179,26,30,343.253,19,3,0,0,8
162,33,14,04/03/2016,248,25,47,343.253,32,1,2,1,3
163,20,13,04/03/2016,260,50,36,343.253,23,1,4,0,40
164,17,11,07/03/2016,179,22,40,343.253,22,2,2,0,40
165,14,1,14/03/2016,155,12,34,343.253,25,1,2,0,16
166,20,26,21/03/2016,260,50,36,343.253,23,1,4,0,16
167,14,13,22/03/2016,155,12,34,343.253,25,1,2,0,8
168,11,6,24/03/2016,289,36,33,343.253,30,1,2,1,8
169,17,8,24/03/2016,179,22,40,343.253,22,2,2,0,8
170,20,28,25/03/2016,260,50,36,343.253,23,1,4,0,4
171,28,23,25/03/2016,225,26,28,343.253,24,1,1,2,1
172,7,14,28/03/2016,279,5,39,343.253,24,1,2,0,8
173,3,13,29/03/2016,179,51,38,343.253,31,1,0,0,24
174,28,23,30/03/2016,225,26,28,343.253,24,1,1,2,2
175,28,11,28/03/2016,225,26,28,343.253,24,1,1,2,8
176,22,13,28/03/2016,179,26,30,343.253,19,3,0,0,1
177,28,11,29/03/2016,225,26,28,343.253,24,1,1,2,8
178,28,11,30/03/2016,225,26,28,343.253,24,1,1,2,16
179,3,13,30/03/2016,179,51,38,343.253,31,1,0,0,3
180,7,14,17/03/2016,279,5,39,343.253,24,1,2,0,16
181,28,28,18/03/2016,225,26,28,343.253,24,1,1,2,2
182,33,14,25/03/2016,248,25,47,343.253,32,1,2,1,3
183,28,28,28/03/2016,225,26,28,343.253,24,1,1,2,1
184,15,28,06/04/2016,291,31,40,326.452,25,1,1,1,1
185,28,23,13/04/2016,225,26,28,326.452,24,1,1,2,1
186,14,28,12/04/2016,155,12,34,326.452,25,1,2,0,1
187,24,13,13/04/2016,246,25,41,326.452,23,1,0,0,24
188,14,23,14/04/2016,155,12,34,326.452,25,1,2,0,1
189,28,28,15/04/2016,225,26,28,326.452,24,1,1,2,2
190,20,28,15/04/2016,260,50,36,326.452,23,1,4,0,4
191,3,13,06/04/2016,179,51,38,326.452,31,1,0,0,24
192,36,23,07/04/2016,118,13,50,326.452,31,1,1,0,1
193,15,23,08/04/2016,291,31,40,326.452,25,1,1,1,3
194,24,14,08/04/2016,246,25,41,326.452,23,1,0,0,8
195,15,28,22/04/2016,291,31,40,326.452,25,1,1,1,1
196,33,28,29/04/2016,248,25,47,326.452,32,1,2,1,8
197,20,19,29/04/2016,260,50,36,326.452,23,1,4,0,56
198,11,19,26/04/2016,289,36,33,326.452,30,1,2,1,8
199,14,12,27/04/2016,155,12,34,326.452,25,1,2,0,24
200,23,19,27/04/2016,378,49,36,326.452,21,1,2,4,8
201,11,13,28/04/2016,289,36,33,326.452,30,1,2,1,16
202,1,7,08/04/2016,235,11,37,326.452,29,3,1,1,3
203,2,0,04/04/2016,235,29,48,326.452,33,1,1,5,0
204,11,13,04/05/2016,289,36,33,378.884,30,1,2,1,8
205,14,28,05/05/2016,155,12,34,378.884,25,1,2,0,2
206,14,28,02/05/2016,155,12,34,378.884,25,1,2,0,1
207,3,18,03/05/2016,179,51,38,378.884,31,1,0,0,8
208,28,19,03/05/2016,225,26,28,378.884,24,1,1,2,8
209,27,7,11/05/2016,184,42,27,378.884,21,1,0,0,4
210,14,28,09/05/2016,155,12,34,378.884,25,1,2,0,2
211,3,12,10/05/2016,179,51,38,378.884,31,1,0,0,1
212,11,13,04/05/2016,289,36,33,378.884,30,1,2,1,24
213,7,0,11/05/2016,279,5,39,378.884,24,1,2,0,0
214,18,0,18/05/2016,330,16,28,378.884,25,2,0,0,0
215,23,0,25/05/2016,378,49,36,378.884,21,1,2,4,0
216,31,0,25/05/2016,388,15,50,378.884,24,1,0,0,0
217,3,11,24/05/2016,179,51,38,378.884,31,1,0,0,1
218,36,13,11/05/2016,118,13,50,378.884,31,1,1,0,24
219,10,22,27/05/2016,361,52,28,378.884,27,1,1,4,8
220,24,19,06/06/2016,246,25,41,377.550,23,1,0,0,8
221,10,22,13/06/2016,361,52,28,377.550,27,1,1,4,8
222,24,10,14/06/2016,246,25,41,377.550,23,1,0,0,24
223,15,23,16/06/2016,291,31,40,377.550,25,1,1,1,4
224,24,10,17/06/2016,246,25,41,377.550,23,1,0,0,8
225,3,11,13/06/2016,179,51,38,377.550,31,1,0,0,8
226,14,23,20/06/2016,155,12,34,377.550,25,1,2,0,4
227,24,10,27/06/2016,246,25,41,377.550,23,1,0,0,8
228,36,13,29/06/2016,118,13,50,377.550,31,1,1,0,8
229,1,13,03/06/2016,235,11,37,377.550,29,3,1,1,16
230,36,23,07/06/2016,118,13,50,377.550,31,1,1,0,1
231,36,13,08/06/2016,118,13,50,377.550,31,1,1,0,80
232,23,22,09/06/2016,378,49,36,377.550,21,1,2,4,8
233,3,11,10/06/2016,179,51,38,377.550,31,1,0,0,2
234,32,28,20/06/2016,289,48,49,377.550,36,1,0,2,2
235,28,28,30/06/2016,225,26,28,377.550,24,1,1,2,2
236,14,19,05/07/2016,155,12,34,275.312,25,1,2,0,16
237,36,1,06/07/2016,118,13,50,275.312,31,1,1,0,8
238,34,5,08/07/2016,118,10,37,275.312,28,1,0,0,8
239,34,26,08/07/2016,118,10,37,275.312,28,1,0,0,4
240,18,26,12/07/2016,330,16,28,275.312,25,2,0,0,8
241,22,18,14/07/2016,179,26,30,275.312,19,3,0,0,8
242,14,25,15/07/2016,155,12,34,275.312,25,1,2,0,2
243,18,1,18/07/2016,330,16,28,275.312,25,2,0,0,8
244,18,1,19/07/2016,330,16,28,275.312,25,2,0,0,8
245,30,25,18/07/2016,157,27,29,275.312,22,1,0,0,3
246,10,22,19/07/2016,361,52,28,275.312,27,1,1,4,8
247,11,26,20/07/2016,289,36,33,275.312,30,1,2,1,8
248,3,26,21/07/2016,179,51,38,275.312,31,1,0,0,8
249,11,19,11/07/2016,289,36,33,275.312,30,1,2,1,32
250,11,19,14/07/2016,289,36,33,275.312,30,1,2,1,8
251,20,0,21/07/2016,260,50,36,275.312,23,1,4,0,0
252,11,19,04/08/2016,289,36,33,265.615,30,1,2,1,8
253,30,19,11/08/2016,157,27,29,265.615,22,1,0,0,3
254,11,23,07/08/2016,289,36,33,265.615,30,1,2,1,1
255,9,18,08/08/2016,228,14,58,265.615,22,1,2,1,8
256,26,13,10/08/2016,300,26,43,265.615,25,1,2,1,1
257,26,14,10/08/2016,300,26,43,265.615,25,1,2,1,2
258,20,28,11/08/2016,260,50,36,265.615,23,1,4,0,4
259,11,23,08/08/2016,289,36,33,265.615,30,1,2,1,4
260,33,23,09/08/2016,248,25,47,265.615,32,1,2,1,1
261,21,11,10/08/2016,268,11,33,265.615,25,2,0,0,8
262,22,23,10/08/2016,179,26,30,265.615,19,3,0,0,1
263,36,13,10/08/2016,118,13,50,265.615,31,1,1,0,3
264,33,25,14/08/2016,248,25,47,265.615,32,1,2,1,2
265,1,23,15/08/2016,235,11,37,265.615,29,3,1,1,1
266,36,23,17/08/2016,118,13,50,265.615,31,1,1,0,1
267,1,19,24/08/2016,235,11,37,265.615,29,3,1,1,8
268,10,8,08/08/2016,361,52,28,265.615,27,1,1,4,8
269,27,6,30/08/2016,184,42,27,265.615,21,1,0,0,8
270,3,11,05/09/2016,179,51,38,294.217,31,1,0,0,8
271,3,23,09/09/2016,179,51,38,294.217,31,1,0,0,3
272,11,19,07/09/2016,289,36,33,294.217,30,1,2,1,24
273,5,0,08/09/2016,235,20,43,294.217,38,1,1,0,0
274,24,9,12/09/2016,246,25,41,294.217,23,1,0,0,16
275,15,28,13/09/2016,291,31,40,294.217,25,1,1,1,3
276,8,0,13/09/2016,231,35,39,294.217,35,1,2,2,0
277,19,0,13/09/2016,291,50,32,294.217,23,1,0,0,0
278,3,13,14/09/2016,179,51,38,294.217,31,1,0,0,8
279,24,9,14/09/2016,246,25,41,294.217,23,1,0,0,32
280,3,23,15/09/2016,179,51,38,294.217,31,1,0,0,1
281,15,28,16/09/2016,291,31,40,294.217,25,1,1,1,4
282,20,28,16/09/2016,260,50,36,294.217,23,1,4,0,4
283,5,26,14/09/2016,235,20,43,294.217,38,1,1,0,8
284,36,28,15/09/2016,118,13,50,294.217,31,1,1,0,1
285,5,0,15/09/2016,235,20,43,294.217,38,1,1,0,0
286,15,28,16/09/2016,291,31,40,294.217,25,1,1,1,3
287,15,7,26/09/2016,291,31,40,294.217,25,1,1,1,40
288,3,13,26/09/2016,179,51,38,294.217,31,1,0,0,8
289,11,24,05/10/2016,289,36,33,265.017,30,1,2,1,8
290,1,26,05/10/2016,235,11,37,265.017,29,3,1,1,4
291,11,26,05/10/2016,289,36,33,265.017,30,1,2,1,8
292,11,22,06/10/2016,289,36,33,265.017,30,1,2,1,8
293,36,0,06/10/2016,118,13,50,265.017,31,1,1,0,0
294,33,0,06/10/2016,248,25,47,265.017,32,1,2,1,0
295,22,1,12/10/2016,179,26,30,265.017,19,3,0,0,8
296,34,7,12/10/2016,118,10,37,265.017,28,1,0,0,3
297,13,22,12/10/2016,369,17,31,265.017,25,1,3,0,8
298,3,28,14/10/2016,179,51,38,265.017,31,1,0,0,1
299,22,1,14/10/2016,179,26,30,265.017,19,3,0,0,64
300,5,0,14/10/2016,235,20,43,265.017,38,1,1,0,0
301,11,19,15/10/2016,289,36,33,265.017,30,1,2,1,16
302,20,28,16/10/2016,260,50,36,265.017,23,1,4,0,3
303,5,0,16/10/2016,235,20,43,265.017,38,1,1,0,0
304,5,23,19/10/2016,235,20,43,265.017,38,1,1,0,2
305,5,23,19/10/2016,235,20,43,265.017,38,1,1,0,2
306,36,28,20/10/2016,118,13,50,265.017,31,1,1,0,1
307,15,28,20/10/2016,291,31,40,265.017,25,1,1,1,4
308,22,23,22/10/2016,179,26,30,265.017,19,3,0,0,16
309,36,28,22/10/2016,118,13,50,265.017,31,1,1,0,1
310,10,10,26/10/2016,361,52,28,265.017,27,1,1,4,8
311,20,0,27/10/2016,260,50,36,265.017,23,1,4,0,0
312,15,0,27/10/2016,291,31,40,265.017,25,1,1,1,0
313,30,0,27/10/2016,157,27,29,265.017,22,1,0,0,0
314,22,1,28/10/2016,179,26,30,265.017,19,3,0,0,5
315,22,7,28/10/2016,179,26,30,265.017,19,3,0,0,5
316,36,23,29/10/2016,118,13,50,265.017,31,1,1,0,1
317,34,11,07/11/2016,118,10,37,284.031,28,1,0,0,8
318,33,23,07/11/2016,248,25,47,284.031,32,1,2,1,2
319,3,6,08/11/2016,179,51,38,284.031,31,1,0,0,8
320,20,28,11/11/2016,260,50,36,284.031,23,1,4,0,3
321,15,23,14/11/2016,291,31,40,284.031,25,1,1,1,1
322,23,1,14/11/2016,378,49,36,284.031,21,1,2,4,8
323,14,11,14/11/2016,155,12,34,284.031,25,1,2,0,120
324,5,26,14/11/2016,235,20,43,284.031,38,1,1,0,8
325,18,0,15/11/2016,330,16,28,284.031,25,2,0,0,0
326,1,18,16/11/2016,235,11,37,284.031,29,3,1,1,1
327,34,11,16/11/2016,118,10,37,284.031,28,1,0,0,3
328,1,25,17/11/2016,235,11,37,284.031,29,3,1,1,2
329,3,28,17/11/2016,179,51,38,284.031,31,1,0,0,3
330,24,13,18/11/2016,246,25,41,284.031,23,1,0,0,8
331,15,12,18/11/2016,291,31,40,284.031,25,1,1,1,4
332,24,13,21/11/2016,246,25,41,284.031,23,1,0,0,8
333,3,28,22/11/2016,179,51,38,284.031,31,1,0,0,1
334,20,10,23/11/2016,260,50,36,284.031,23,1,4,0,8
335,20,15,25/11/2016,260,50,36,284.031,23,1,4,0,8
336,23,0,25/11/2016,378,49,36,284.031,21,1,2,4,0
337,7,0,29/11/2016,279,5,39,284.031,24,1,2,0,0
338,3,23,24/11/2016,179,51,38,284.031,31,1,0,0,1
339,28,12,05/12/2016,225,26,28,236.629,24,1,1,2,3
340,3,28,05/12/2016,179,51,38,236.629,31,1,0,0,2
341,3,28,05/12/2016,179,51,38,236.629,31,1,0,0,1
342,1,23,05/12/2016,235,11,37,236.629,29,3,1,1,3
343,36,28,06/12/2016,118,13,50,236.629,31,1,1,0,1
344,20,28,09/12/2016,260,50,36,236.629,23,1,4,0,4
345,24,4,15/12/2016,246,25,41,236.629,23,1,0,0,8
346,3,28,15/12/2016,179,51,38,236.629,31,1,0,0,1
347,3,28,16/12/2016,179,51,38,236.629,31,1,0,0,1
348,22,23,20/12/2016,179,26,30,236.629,19,3,0,0,1
349,34,25,20/12/2016,118,10,37,236.629,28,1,0,0,8
350,1,25,22/12/2016,235,11,37,236.629,29,3,1,1,2
351,3,28,23/12/2016,179,51,38,236.629,31,1,0,0,1
352,5,13,20/12/2016,235,20,43,236.629,38,1,1,0,8
353,1,14,20/12/2016,235,11,37,236.629,29,3,1,1,4
354,20,26,21/12/2016,260,50,36,236.629,23,1,4,0,8
355,30,28,19/12/2016,157,27,29,236.629,22,1,0,0,2
356,3,28,19/12/2016,179,51,38,236.629,31,1,0,0,3
357,11,19,19/12/2016,289,36,33,236.629,30,1,2,1,8
358,28,23,04/01/2017,225,26,28,330.061,24,1,1,2,5
359,34,19,09/01/2017,118,10,37,330.061,28,1,0,0,32
360,14,23,09/01/2017,155,12,34,330.061,25,1,2,0,2
361,1,13,03/01/2017,235,11,37,330.061,29,3,1,1,1
362,14,23,03/01/2017,155,12,34,330.061,25,1,2,0,4
363,11,26,09/01/2017,289,36,33,330.061,30,1,2,1,8
364,15,3,11/01/2017,291,31,40,330.061,25,1,1,1,8
365,5,26,16/01/2017,235,20,43,330.061,38,1,1,0,8
366,36,26,16/01/2017,118,13,50,330.061,31,1,1,0,4
367,3,28,25/01/2017,179,51,38,330.061,31,1,0,0,1
368,3,28,27/01/2017,179,51,38,330.061,31,1,0,0,1
369,34,28,07/02/2017,118,10,37,251.818,28,1,0,0,2
370,3,27,01/02/2017,179,51,38,251.818,31,1,0,0,3
371,28,7,01/02/2017,225,26,28,251.818,24,1,1,2,1
372,11,22,03/02/2017,289,36,33,251.818,30,1,2,1,3
373,20,28,10/02/2017,260,50,36,251.818,23,1,4,0,3
374,3,23,17/02/2017,179,51,38,251.818,31,1,0,0,3
375,3,27,13/02/2017,179,51,38,251.818,31,1,0,0,2
376,3,27,15/02/2017,179,51,38,251.818,31,1,0,0,3
377,3,10,16/02/2017,179,51,38,251.818,31,1,0,0,8
378,24,26,16/02/2017,246,25,41,251.818,23,1,0,0,8
379,3,27,17/02/2017,179,51,38,251.818,31,1,0,0,3
380,6,22,13/02/2017,189,29,33,251.818,25,1,2,2,8
381,3,27,13/02/2017,179,51,38,251.818,31,1,0,0,3
382,24,23,21/02/2017,246,25,41,251.818,23,1,0,0,2
383,15,23,21/02/2017,291,31,40,251.818,25,1,1,1,2
384,30,11,22/02/2017,157,27,29,251.818,22,1,0,0,16
385,3,27,22/02/2017,179,51,38,251.818,31,1,0,0,3
386,3,27,24/02/2017,179,51,38,251.818,31,1,0,0,3
387,24,10,24/02/2017,246,25,41,251.818,23,1,0,0,24
388,3,27,22/02/2017,179,51,38,251.818,31,1,0,0,3
389,3,27,24/02/2017,179,51,38,251.818,31,1,0,0,3
390,34,18,07/03/2017,118,10,37,244.387,28,1,0,0,8
391,24,19,08/03/2017,246,25,41,244.387,23,1,0,0,16
392,24,28,10/03/2017,246,25,41,244.387,23,1,0,0,2
393,20,28,10/03/2017,260,50,36,244.387,23,1,4,0,4
394,3,28,13/03/2017,179,51,38,244.387,31,1,0,0,2
395,1,22,13/03/2017,235,11,37,244.387,29,3,1,1,8
396,17,22,14/03/2017,179,22,40,244.387,22,2,2,0,8
397,23,22,14/03/2017,378,49,36,244.387,21,1,2,4,8
398,3,28,20/03/2017,179,51,38,244.387,31,1,0,0,16
399,10,22,22/03/2017,361,52,28,244.387,27,1,1,4,8
400,13,0,22/03/2017,369,17,31,244.387,25,1,3,0,0

In [16]:
# Information of the Dataset
raw_csv_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
ID                           700 non-null int64
Reason for Absence           700 non-null int64
Date                         700 non-null object
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB